# Generated by Django 4.1.5 on 2023-01-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_imageblog_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageBlog',
            new_name='BlogImage',
        ),
    ]
