# Generated by Django 4.1.5 on 2023-03-07 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='traccia',
            field=models.FileField(blank=True, null=True, upload_to='tracce/', validators=[django.core.validators.FileExtensionValidator(['gpx'])]),
        ),
    ]
